# This file tells Netlify how to build your site and deploy your functions.

[build]
  # The command that Netlify will use to build your site.
  # This runs jekyll build and then installs the npm packages for your functions.
  command = "jekyll build && npm install"
  
  # The directory that contains your built site.
  publish = "_site"

# This section configures the deployment of your serverless functions.
[functions]
  # The directory where your serverless functions are located.
  directory = "netlify/functions"
