backend:
  name: git-gateway
  branch: main # This is usually your main branch, e.g., main or master

media_folder: "/images/blog" # Folder to upload images to
public_folder: "/images/blog" # The public path to the images

collections:
  - name: "templates" # A friendly name for the CMS UI
    label: "Templates" # The label in the sidebar
    folder: "_templates" # The path to your collection folder
    create: true # Allow users to create new templates
    slug: "{{slug}}" # Filename will be based on the title
    fields: # The fields in the front matter of each template file
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "template",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Price",
          name: "price",
          widget: "number",
          value_type: "float",
          min: 0,
        }
      - { label: "Features", name: "features", widget: "list" }

  - name: "blog" # A friendly name for the CMS UI
    label: "Blog" # The label in the sidebar
    folder: "_posts" # The path to your blog post folder
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
