backend:
  name: git-gateway
  branch: main # This is usually your main branch, e.g., main or master

media_folder: "/images/blog" # Folder to upload images to
public_folder: "/images/blog" # The public path to the images

collections:
  - name: "templates"
    label: "Templates"
    folder: "_templates"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "template",
        }

      # HERO SECTION
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Price", name: "price", widget: "number", required: true }
      - { label: "Main Image", name: "image", widget: "image", required: true }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image", required: true }

      # VIDEO (OPTIONAL)
      - {
          label: "YouTube Video ID",
          name: "video",
          widget: "string",
          required: false,
        }
      - {
          label: "Local Video Path",
          name: "local_video",
          widget: "string",
          required: false,
        }

      # PRODUCT CONTENT
      - {
          label: "Short Description",
          name: "description",
          widget: "markdown",
          required: true,
        }
      - {
          label: "Features",
          name: "features",
          widget: "markdown",
          required: false,
        }
      - {
          label: "How It Works",
          name: "how_it_works",
          widget: "markdown",
          required: false,
        }

      # FULL PAGE CONTENT (OPTIONAL)
      - {
          label: "Detailed Info",
          name: "details",
          widget: "markdown",
          required: false,
        }

      # DOWNLOAD (sent via email after Razorpay)
      - {
          label: "Download Link",
          name: "download_link",
          widget: "string",
          required: true,
        }

  - name: "blog" # A friendly name for the CMS UI
    label: "Blog" # The label in the sidebar
    folder: "_posts" # The path to your blog post folder
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "default",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
